add support for sequel
iangreenleaf/transactional_capybara pull request #3
Opened 2017-01-27 13:25 UTC by aiomaster

I want to use this gem with sequel and don't have ActiveRecord in my project.
In sequel you don't have to hack around to share your connections - just add single_threded: true to your connection specification.
But I want to use the ajax magic of this gem, so I make this pull request to make it possible to use sequel and this gem.
What do you think?

2017-01-27 18:33 UTC, iangreenleaf requested changes
This looks great and I would love to add Sequel support to the gem! Thanks for putting this together!

The one thing this definitely needs to be merge-ready is some tests. I may have to make some changes to the spec setup for it to be able to handle multiple DB adapters…

2017-01-27 18:33 UTC, iangreenleaf commented on README.md
> +add the option `single_threaded: true` to your sequel connection in test.
Would it be possible to set this automatically for people? It seems safe to assume that they want it single threaded any time this gem is active.

2017-01-30 16:53 UTC, iangreenleaf commented
Cool, this is pretty much ready! Just let me know if it's possible to set the single-threaded option automatically.

2017-01-31 07:44 UTC, aiomaster commented
Hi @iangreenleaf,
first thanks for your support at this! This is really awesome and motivating! :)

Maybe we should add tests for the connection sharing part.
As far as I see there are no such tests (I can comment out the code in shared_connection/active_record.rb completely and the tests will pass.
If we have such tests we could improve the sequel stuff.
I don't really know if it is possible to set the single_threaded mode after a connection was established.
But maybe yes (or we could close the current connection and reopen one with single_threaded: true).
At least we should warn in logs, that it would be better to set this option in the default test database connection settings. To raise an exception is maybe a bit too heavy, I think.

One last thing: In the docs you say "Right now this gem automatically fixes the following things:",
but for sequel there is not really something to "fix", cause there is this option.
Maybe we should say: "Right now this gem automatically handles the following things:".

So any idea, how we could test connection_sharing?

2017-01-31 11:08 UTC, aiomaster commented
I asked @jeremyevans about enabling the single_threaded option on the fly.
Maybe he has a look and knows better than me.

2017-01-31 17:02 UTC, aiomaster commented
Jeremy says:

> There isn't a supported method to do so.  You can try this:
> 
>   DB.disconnect
>   DB.instance_variable_set(:@pool,
>     Sequel::ConnectionPool.get_pool(DB,
>       DB.opts.merge(:single_threaded=>true)))
> 
> But it is not supported and won't be supported in the future.  If the
> code only supports the single threaded pool, you should probably raise
> an exception if the database isn't single threaded.
> 
> Thanks,
> Jeremy

so maybe we should keep the exception raise. What do you think, @iangreenleaf?

2017-01-31 18:19 UTC, iangreenleaf commented
> Maybe we should add tests for the connection sharing part.

You're right, I thought I had tests that would fail without the shared connection but trying it I see they still pass. Would be great to have that tested too, but I'm happy to go ahead with this PR without that, especially given that we might not be sharing the connection for Sequel…

> Jeremy says: […] so maybe we should keep the exception raise.

Agreed that hack looks ugly and probably isn't worth it. However, I'm leaning towards the idea of making it a WARN + no-op instead. My thinking is that this gem doesn't actually *need* the connection to be shared. Generally people want it to be shared for things like transactions, but this just helps them deal with the consequences. So if someone really wants to run this with an un-shared connection, we don't actually have to stop them.

>  Maybe we should say: "Right now this gem automatically handles the following things:".

Sure, "handles" makes sense. Or "supports" might work too. I struggled on the wording of that section, since it's listing several different layers of technology 😃

2017-02-01 08:48 UTC, aiomaster commented
I agree, so I added the warning.
The connection sharing tests are another story: #5

Thanks for maintaining that gem!

2017-03-27 03:10 UTC, iangreenleaf approved these changes

2017-03-27 03:13 UTC, iangreenleaf commented
Hey, I am so sorry for abandoning this issue! Life came at me crazy and this got pushed too far down my inbox and I forgot about it. Thanks for all your work on this patch! Happy to merge it in now.

2017-03-27 03:13 UTC, merged